stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/insurance.csv
    outs:
    - data/raw/dataset.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/dataset.csv
    outs:
    - data/processed/train_dataset.csv
    - data/processed/test_dataset.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/test_dataset.csv
    - data/processed/train_dataset.csv
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.criterion
    - estimators.RandomForestRegressor.params.max_depth
    - estimators.RandomForestRegressor.params.min_samples_split
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - models/model.joblib